language: java
# for an overview see https://docs.travis-ci.com/user/reference/overview/

os:
 - linux
 
dist: trusty

cache:
    directories:
        - $HOME/.m2

jobs:
    include:  
        - name: "JDK: openjdk8 + coverage"
          jdk: openjdk8
          script: cd ./jpa && mvn clean verify 
          after_success:
              - mvn -q test jacoco:report
        - name: "JDK: sapmachine11"
          before_install:
            - curl -s "https://get.sdkman.io" | bash
            - source "$HOME/.sdkman/bin/sdkman-init.sh"
            - sdk install java 11.0.14-sapmchn
            - sdk use java 11.0.14-sapmchn
          script: cd ./jpa && mvn -q verify
        - name: "JDK: sapmachine17"
          before_install:
            - curl -s "https://get.sdkman.io" | bash
            - source "$HOME/.sdkman/bin/sdkman-init.sh"
            - sdk install java 17.0.2-sapmchn
            - sdk use java 17.0.2-sapmchn
          script: cd ./jpa && mvn -q verify          
        - name: "JDK: oraclejdk8"
          jdk: oraclejdk8
          script: cd ./jpa && mvn -q verify   

branches:
    only:
        - master
        - develop
notifications:
  email:
    on_success: change
    on_failure: always        
