general:
  buildTool: 'maven'
  productiveBranch: 'master'
  vaultPath: 'piper/sap-project-odata-jpa-3ab8029f-91ea-45a4-a943-bac0e44a0db6'
  vaultBasePath: 'piper/sap-project-odata-jpa-3ab8029f-91ea-45a4-a943-bac0e44a0db6'
  vaultPipelineName: 'odata-v4-jpa-processor'
  vaultServerUrl: 'https://vault.tools.sap'
  vaultNamespace: 'ies/hyperspace/pipelines'
  nativeBuild: true
stages:
  Release:
    sapDownloadArtifact: false
  Post:
    # Secret rotation handled by Hyperspace Portal, enabling it back might cause unintended behavior
    vaultRotateSecretId: false
steps:
  sapCallStagingService:
    url: 'https://staging.repositories.cloud.sap/stage/api'
    profile: 'group-odata-jpa-gnmtd-default'
  sonarExecuteScan:
    serverUrl: 'https://sonar.tools.sap'
  sapCumulusUpload:
    pipelineId: 'a9cd03e0-93fe-4dc8-864f-e5f74d27a4c6'
