logging:
  level:
    org:
      springframework: DEBUG
odata:
  jpa:
    punit_name: ${punit}
    request_mapping: requestMapping
    root_packages: ${package}
server:
  port: 9010
spring:
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    password: ''
    url: jdbc:hsqldb:mem:${punit};DB_CLOSE_DELAY=-1
    username: sa
  flyway:
    password: ''
    schemas:
    - ${schema}
    url: jdbc:hsqldb:mem:${punit};DB_CLOSE_DELAY=-1
    user: sa
  servlet:
    multipart:
      enabled: false
